apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-{{ .Values.project.env }}
  namespace: {{ include "project.name" . }}
  labels:
{{ include "project.labels" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
{{ include "project.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "project.labels" . | indent 8 }}
      annotations:
        timestamp: "{{ now | unixEpoch }}"
    spec:
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end -}}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end -}}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: consumer-{{ .Values.project.env }}
          image: "{{ .Values.app.image }}:{{ .Values.project.tag }}"
          imagePullPolicy: {{ .Values.app.imagePullPolicy}}
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "sleep 5; /usr/bin/supervisorctl start all" ]
          resources:
            limits:
              cpu: 1
              memory: "2Gi"
            requests:
              cpu: 1
              memory: "256Mi"
          ports:
            - containerPort: 9001
