{{- if .Values.database.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "project.fullname" . }}-db-migrate
  namespace: {{ include "project.name" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
{{ include "project.labels" . | indent 4 }}
spec:
  activeDeadlineSeconds: 180
  template:
    spec:
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: "{{ .Values.app.image }}:{{ .Values.project.tag }}"
          imagePullPolicy: {{ .Values.app.imagePullPolicy}}
          command: [ "/usr/bin/php", "/var/www/app/console", "doctrine:migrations:migrate", "-n", "--env=prod" ]
{{- end }}