apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project.fullname" . }}
  namespace: {{ include "project.name" . }}
  labels:
{{ include "project.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
{{ include "project.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "project.labels" . | indent 8 }}
      annotations:
        timestamp: "{{ now | unixEpoch }}"
    spec:
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end -}}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end -}}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ include "project.fullname" . }}-app
          image: "{{ .Values.app.image }}:{{ .Values.project.tag }}"
          imagePullPolicy: {{ .Values.app.imagePullPolicy}}
          {{- if .Values.app.resources }}
          resources:
            limits:
              cpu: {{ .Values.app.resources.limits.cpu }}
              memory: {{ .Values.app.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.app.resources.requests.cpu }}
              memory: {{ .Values.app.resources.requests.memory | quote }}
          {{- end }}
          ports:
            - containerPort: 9000
              name: php-fpm
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 15
            timeoutSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            timeoutSeconds: 10
        - name: {{ include "project.fullname" . }}-web
          image: "{{ .Values.web.image }}:{{ .Values.project.tag }}"
          imagePullPolicy: {{ .Values.web.imagePullPolicy}}
          {{- if .Values.web.resources }}
          resources:
            limits:
              cpu: {{ .Values.web.resources.limits.cpu }}
              memory: {{ .Values.web.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.web.resources.requests.cpu }}
              memory: {{ .Values.web.resources.requests.memory | quote }}
          {{- end }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 10
          env:
            - name: TZ
              value: "Europe/Moscow"
